sudo: required
language: go
go:
- tip
before_install:
- curl -sfL https://raw.githubusercontent.com/apex/up/master/install.sh | sudo sh
- sudo up upgrade
deploy:
  provider: script
  script: up
  on:
    branch: master
