sudo: required
language: go
go:
- tip
before_install:
- curl -sf https://up.apex.sh/install | sudo sh
- sudo up upgrade
deploy:
    - provider: script
      skip_cleanup: true
      script: up deploy
      on:
        branch: master
