sudo: required
language: go
go:
- tip
before_install:
- curl -sf https://up.apex.sh/install | sudo sh
- sudo up upgrade
deploy:
    - provider: script
      skip_cleanup: true
      script: up -C $TRAVIS_BUILD_DIR/up -v deploy
      on:
        branch: master
