sudo: required
language: go
go:
- tip
before_install:
- curl -sfL https://raw.githubusercontent.com/apex/up/master/install.sh | sudo sh
- up upgrade
after_success:
- test "$TRAVIS_BRANCH" = master && up
