sudo: required
language: go
go:
- tip
before_install:
- curl -sf https://up.apex.sh/install | sudo sh
- sudo up upgrade
deploy:
  provider: script
  script: cd up && echo $(date) && up -v
  on:
    branch: master
